In [1]:
import numpy as np

In [65]:
a = np.matrix([[1],[3],[5]])
b = np.matrix([[7],[11],[13]])
c = np.array([3,4,5,6,7])




In [28]:
print(np.shape(a))
print(a.ndim)
print(c.shape)

(5,)
1
(5,)


In [66]:
d = np.dot(a,b)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [63]:
print(d)

105


In [54]:
print(a*b)

[[ 96 114 132]
 [284 346 408]
 [508 626 744]]
